### ISSUE TITLE
Error while generating English dataset

### ISSUE THREAD

**Issue by jayavanth** [carpedm20/multi-speaker-tacotron-tensorflow#17]
Data preparation runs fine but generation fails.
```
$  python3 -m datasets.generate_data ./datasets/LJSpeech_1_0
========================================
 [!] Sampling rate: 22050
========================================

Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/jay/multi-speaker-tacotron-tensorflow/datasets/generate_data.py", line 191, in <module>
    build_from_path(config)
  File "/home/jay/multi-speaker-tacotron-tensorflow/datasets/generate_data.py", line 50, in build_from_path
    raise Exception(" [!] Unkown metadata format: {}".format(config.metadata_path))
Exception:  [!] Unkown metadata format: ./datasets/LJSpeech_1_0
```

**Comment by engiecat** [comment]
uhm there is an error in readme
you should do
python3 -m datasets.generate_data ./datasets/LJSpeech_1_0/alignment.json

**Comment by jayavanth** [comment]
I can just see the loading icon spinning when I click `Synthesize`. I put the trained model files in `logs/LJSpeech_1_0_2018-02-08_13-26-31` and ran `python3 app.py --load_path logs/LJSpeech_1_0_2018-02-08_13-26-31 --num_speakers=1 --is_korean=False` Do you know why that might be?

**Comment by engiecat** [comment]
@jayavanth You should modify web/static/js/main.js line 99
from `generate('0.0.0.0', 51000, text, speaker_id);` to 'generate(YOUR_COMPUTER_IP, 51000, text, speaker_id);'.
