### ISSUE TITLE
생성된 wav 파일을 미디어플레이어에서 실행하면 지원하지 않는 형식이라고 나옵니다.

### ISSUE THREAD

**Issue by weegwangjin** [carpedm20/multi-speaker-tacotron-tensorflow#21]
500step 까지 돌리고 test로 나온 wav 파일을 실행시켜보려는데 지원하지 않는 형식이라고 나옵니다.
그래서 vcl player에서 재생해봤는데 거의 아무소리도 들리지 않고 다른 분들 파일은 미디어플레이어에서도 잘 실행되는 것 같은데 어디서 문제가 생긴걸까요?

**Comment by weegwangjin** [comment]
현재 7000step 이상 진행했고, png 파일 열어보면 스펙트럼은 어느정도 보이는데
wav파일 열어도 아무소리도 안들리네요...
특히 그냥 일반적인 플레이어로는 실행하면 지원하지 않는 형식이라고 나오고
vcl player로 어떻게 열리긴 하는데 아무소리가 안들립니다.
아직 학습이 덜되서 그런걸까요? 

맨 처음 git clone 해서 받은 파일을 학습시키려니까 data must be floating point 라고 해서
소스를 제가 고쳤거든요
librosa.output.write_wav(path, audio.astype(np.float64),
            hparams.sample_rate if sample_rate is None else sample_rate)
audio/init.py 부분입니다.
원래는 np.float64가 np.int 로 되어있어서 audio valid 검사에서 에러가 났던거였더라구요
저기서 고치는게 맞는 건가요?

**Comment by jwlee2218** [comment]
으음 저는 data must be floating point에서 막혀있었네요
혹시 step 이 진행되면서 문제가 해결되었나요? 그렇다면 님께서 하신 방법을 사용해보려고 합니다..!

**Comment by weegwangjin** [comment]
@jwlee2218 
저도 계속 조사해봤는데 float으로 넘겨주면 소리가 나질 않더라구요
우선 원래 코드인 int16으로 넘겨주는게 맞는 것 같은데
저는 일단 librosa에서 valid하는 코드를 주석처리하고 학습중이긴 합니다.

좀 더 찾아봐야 할 것 같고, 말씀해주신 부분은 저는 float으로 고치고 에러나지 않고 5만 step까지 진행이 잘 됬습니다.
그리고 wav 파일을 16비트로 저장해야 되는데 float64로 바꾸는 것도 잘못된 것 같습니다.
