### ISSUE TITLE
train.py가 트레이닝을 시작하지 못합니다

### ISSUE THREAD

**Issue by rycont** [carpedm20/multi-speaker-tacotron-tensorflow#34]
![image](https://user-images.githubusercontent.com/35295182/41804496-50899c60-76d2-11e8-8eaf-829d2ed67a69.png)
여기서처럼

```
filter_by_min_max_frame_batch: 0it [00:00, ?it/s]
 [datasets/egoing\data] Loaded metadata for 0 examples (0.00 hours)
========================================
{'datasets/egoing\\data': 1.0}

```
만 뜨고 학습이 진행되지 않습니다. 현재 40분정도 기다린것같습니다. 원래 이렇게 오래걸리나요? 아니면 세팅이 잘못된건지 여쭤보고싶습니다.

**Comment by wyb330** [comment]
학습할 데이터가 0이라 그런 것으로 보입니다.
아마도 전처리 과정을 안했거나 학습 데이터 경로가 잘못된 것 같습니다.

**Comment by Jiwonkim93** [comment]
저도 이 상태인데 혹시 해결하셨나요??ㅠㅠ

**Comment by rycont** [comment]
python3 -m datasets.generate_data ./datasets/YOUR_DATASET/alignment.json

이 명령으로 데이터를 생성했더니 되었습니다!
