### ISSUE TITLE
Tensorflow 에 대한 문제

### ISSUE THREAD

**Issue by hansolc** [carpedm20/multi-speaker-tacotron-tensorflow#49]
제 그래픽 카드가 라데온이기 때문에
tensorflow을 pin을 이용해 가상환경에서 받았습니다.
tacotron을 이용하려면 tensorflow 1.3 version으로 이용해야 하는 것으로 알고 있는데
업데이트 명령어를 사용해 주어도 1.11.0-rc0 버전 이상으로 올라가지 않습니다.
혹시 해결할 수 있는 방법이 있을까요?

다른 싸이트에서는 
pip install --upgrade --pre tensorflow
해당 명령어를 이용해 1.9version이 release 되었다고 해서 해 보았는데
1.0.1 -> 1.11 로 업데이트 되고 그 이상은 업데이트가 되지 않는것 같습니다.

keras 2.2.2 has requirement keras-applications==1.0.4, but you'll have keras-applications 1.0.5 which is incompatible.
keras 2.2.2 has requirement keras-preprocessing==1.0.2, but you'll have keras-preprocessing 1.0.3 which is incompatible.

해당 오류가 함께 발생하는데 혹시 이 문제 인가요?

아니면 그래픽카드가 라데온이 아닌 엔디비아로 교체해서 사용 해야하는 건가요?

**Comment by rockpro87** [comment]
tensorflow 1.3버전은 1.11버전보다 하위버전입니다.
pip install tensorflow==1.3.0 으로 설치하시면 됩니다~
그리고 그래픽카드는 nvidia만 지원하는 걸로 알고있는데 (CUDA코어를 지원해야 하니까) 확인해보세요

**Comment by hansolc** [comment]
감사합니다~~
해결했습니다
