### ISSUE TITLE
Generated audio is silent while training Urdu language

### ISSUE THREAD

**Issue by Usama0121** [carpedm20/multi-speaker-tacotron-tensorflow#65]
Hi,
	I am training the multi-speaker model that consists of 50 speakers and data is around 75 hours. I defined symbols for Urdu language in symbols.py and also added a cleaner in cleaners.py. Successfully pre-processed the data and now have completed more then 110K steps. The train audios are giving quite good results but the test audios are only producing noise or silence.

**Comment by TaoTaoFu** [comment]
hello, my friend.  I also meet the same problem as you excepting  I use English datasets.  my train_audio is  very well, but the test_audio is  just silence. Do you solve the problem now?

**Comment by Usama0121** [comment]
Hi,
Unfortunately, the issue wasn't resolved. So I used tacotron's implementation by [Keith Ito](https://github.com/keithito/tacotron). I used a single speaker data of around 1 hour and trained the model starting from the pre-trained model available at the repo

**Comment by saharsyed** [comment]
was your second attempt for english tts or urdu?

**Comment by Usama0121** [comment]
@saharsyed
It was for Urdu
