### ISSUE TITLE
500step 오류

### ISSUE THREAD

**Issue by BlueDragon20148** [carpedm20/multi-speaker-tacotron-tensorflow#69]
500step진행 때 자꾸 cancellederror (see above for traceback) enqueue operation was cancelled 이런 오류가 떠서 포기할까 생각 중인데 어떻게 해야 하나요?

**Comment by garam-park** [comment]
500 스텝 마다 데이터를 저장하는데 폴더 권한 문제나 그런거 아닐까요..?

**Comment by BlueDragon20148** [comment]
그러면 우분투16.04 쓰는데 어떻게 설정해야 하나요?
