### ISSUE TITLE
14000step인데 이정도면 잘 되고 있는 건가요?

### ISSUE THREAD

**Issue by BlueDragon20148** [carpedm20/multi-speaker-tacotron-tensorflow#71]
![1571450509978](https://user-images.githubusercontent.com/56221230/67136330-e0de7100-f25f-11e9-9870-b00b327a09cc.png)
![1571450508752](https://user-images.githubusercontent.com/56221230/67136333-e3d96180-f25f-11e9-92af-b624a14cc171.png)
이게 테스트 스텝인가 그렇고
![1571450567136](https://user-images.githubusercontent.com/56221230/67136340-fd7aa900-f25f-11e9-89ec-bc21a3568241.png)
이게 트레인 스텝입니다.

그런데 테스트 스텝 목소리 들어보니 처음에 두 음절 정도만 나오고 기계음이 나던데 아직 학습이 덜 되어서 그런건가요?
트레인 스텝은 잘 나오던데

그리고 한글 깨지는 건 어떻게 해결하나요

**Comment by ocean-park** [comment]
한글 깨지는 현상 해결 https://github.com/carpedm20/multi-speaker-tacotron-tensorflow/issues/13 
학습정도는 잘 모르겠네요. 데이터마다 다르다 합니다. 전느 70만 정도 하니 쭉 뻗는 그래프가 보입니다
